Markov 链的矩阵表示

$P_{ij}^{(n)}$ 表示从状态 $i$ 出发第 $n$ 步到达状态 $j$ 的概率。易见，矩阵 $P^n$ 的第 $i$ 行的各个元素表示从状态 $i$ 出发第 $n$ 步时到达列号对应的状态的概率。

Markov 链的有向图表示

每个状态用一个节点表示，生成一个有向完全图，且每个节点带圈。

用边的透明度表示状态的转移概率。

In [ ]:
# 生成一个完全有向图

# 将状态 i 到状态 j 的转移概率设置为边 i -> j 的灰度

# 习题



习题 3.1.1

In [10]:
import numpy as np

# 初始分布
initial_distribution = [0.3, 0.4, 0.3]

# 转移概率矩阵
TPM = np.matrix( [[0.1, 0.2, 0.7],
                  [0.9, 0.1, 0.0],
                  [0.1, 0.8, 0.1]] )

# 一步转移概率
def OneStepTransPr( i, j, TPM, n ):
    return (TPM ** (n+1))[i, j]

In [11]:
initial_distribution[0] * OneStepTransPr( 0, 1, TPM, 0 ) * OneStepTransPr( 1, 2, TPM, 1 )

0.0378

In [13]:
OneStepTransPr( 1, 2, TPM, 0 )

0.0

习题 3.1.2

In [10]:
import numpy as np

# 转移概率矩阵
TPM = np.matrix( [[0.7, 0.2, 0.1],
                  [0.0, 0.6, 0.4],
                  [0.5, 0.0, 0.5]] )

# 一步转移概率
def OneStepTransPr( i, j, TPM, n ):
    return (TPM ** (n+1))[i, j]

In [11]:
initial_distribution[0] * OneStepTransPr( 0, 1, TPM, 0 ) * OneStepTransPr( 1, 2, TPM, 1 )

0.0378

In [13]:
OneStepTransPr( 1, 2, TPM, 0 )

0.0

习题 3.1.3

In [20]:
import numpy as np

# 状态序号集
states = [0, 1, 2]

# 转移概率矩阵, 其中 TPM[i, j] 表示从状态 i 转移到状态 j 的概率
TPM = np.matrix( [[0.6, 0.3, 0.1],
                  [0.3, 0.3, 0.4],
                  [0.4, 0.1, 0.5]] )

# 若状态的初始值为 X0 = 1，则令 X1 的状态分布为初始状态分布
initial_distribution = TPM[1, :]

In [21]:
initial_distribution

matrix([[ 0.3,  0.3,  0.4]])

习题 3.2.1

In [14]:
import numpy as np

# 状态集合
states = [0, 1, 2]

# 转移概率矩阵
TPM = np.matrix( [[0.1, 0.2, 0.7],
                  [0.2, 0.2, 0.6],
                  [0.6, 0.1, 0.3]] )

In [15]:
# 两步转移矩阵
TPM ** 2

matrix([[ 0.47,  0.13,  0.4 ],
        [ 0.42,  0.14,  0.44],
        [ 0.26,  0.17,  0.57]])

In [13]:
OneStepTransPr( 1, 2, TPM, 0 )

0.0

In [17]:
[0.1, 0.2, 0.7] * TPM * [[0.2], [0.2], [0.1]]

matrix([[ 0.16]])

习题 3.2.2

某质点在位置 $0, 1, 2$ 间不断变动，其位置变化过程是一个 Markov 过程，且转移概率矩阵已知，如下所示。令 $X_n$ 表示 $n$ 时刻质点的位置，求 $\Pr(X_n = 0\ |\ X_0 = 0)$, ($n = 0, 1, 2, 3, 4$).

In [ ]:
import numpy as np

# 转移概率矩阵
TPM = np.matrix( [[0.0, 0.5, 0.5],
                  [0.5, 0.0, 0.5],
                  [0.5, 0.5, 0.0]] )

首先我们求一求每一个各个状态出现的概率分布

In [19]:
# X1 的概率分布
X1_dist = [0, 0.5, 0.5]

# X2 的概率分布
X2_dist = X1_dist * TPM

# 下面的程序计算已知第 m 步时的概率分布为 Xm_dist 的情况下，第 n 步时各个状态的概率分布
# 默认 m 是第 0 步时的各个状态的概率分布
def X_dist( n, TPM, initial_dist, m=0 ):
    if n==0:
        return initial_dist
    else:
        return initial_dist * (TPM ** (n-m))

In [24]:
for n in [2, 3, 4]:
    print( "X" + str(n) + " 的概率分布为" + str(X_dist( n, TPM, X1_dist )) )

X2 的概率分布为[[ 0.5   0.25  0.25]]
X3 的概率分布为[[ 0.25   0.375  0.375]]
X4 的概率分布为[[ 0.375   0.3125  0.3125]]


下面的程序直接求出现指定状态的概率

In [12]:
# 设状态间的转移概率矩阵 TPM 已知，矩阵的行号表示第 n 步的状态，列号表示第 n＋1 步的状态
# 下面的程序计算初始状态为 initial_state 的情况下，第 n 步的状态为 state 的概率
# 初始状态默认为第 0 步的状态

def StatePr( state, n, TPM, initial_state):
    # 根据初始状态和概率转移矩阵得到第 1 步后各个状态的概率分布
    X1_dist = TPM[initial_state]
    
    # 根据第 1 步后概率分布和转移概率矩阵得到第 n 步后各个状态的概率分布
    Xn_dist = X1_dist * (TPM ** (n-1))
    
    # 返回状态概率分布中状态 state 的概率
    if n==0:
        return 1
    elif n==1:
        return X1_dist[0, state]
    else:
        return Xn_dist[0, state]

In [15]:
for n in range(5):
    print( "第" + str(n) + "步的状态为0的概率是" + str(StatePr( 0, n, TPM, 0 )) )

第0步的状态为0的概率是1
第1步的状态为0的概率是0.0
第2步的状态为0的概率是0.5
第3步的状态为0的概率是0.25
第4步的状态为0的概率是0.375


习题 3.2.3

In [16]:
import numpy as np

# 转移概率矩阵
TPM = np.matrix( [[0.7, 0.2, 0.1],
                  [0.0, 0.6, 0.4],
                  [0.5, 0.0, 0.5]] )

In [17]:
initial_state = 0
n = 3
state = 1

print( "在初始状态为" + str(initial_state) + "的条件下，第" + str(n) + \
      "步的状态为" + str(state) + "的概率是" + str(StatePr( state, n, TPM, initial_state )) )

在初始状态为0的条件下，第3步的状态为1的概率是0.264


In [18]:
initial_state = 0
n = 4
state = 1

print( "在初始状态为" + str(initial_state) + "的条件下，第" + str(n) + \
      "步的状态为" + str(state) + "的概率是" + str(StatePr( state, n, TPM, initial_state )) )

在初始状态为0的条件下，第4步的状态为1的概率是0.254


# 一个简单的马尔可夫链

在一个随机过程中，如果事件发生的概率在 t 时刻所处的状态为已知时，它在 t+1 时刻只与 t 时刻的状态有关，而与之前所处的状态无关，则称该过程具有马尔可夫性.

时间和状态都是离散的马尔可夫过程称为马尔可夫链. 马尔可夫链在经济学，社会学，生命科学领域有着广泛的应用. 这里举例说明.

例子： 姜华平、陈海泳对某城市 2002 年居民出行方式所占比例进行了调查. 结果如下

公交车(bus), 自行车(Bicycle), 步行(walk), 其他(other)
19%, 14%, 56%, 11%

本时期各出行方式转移概率如下表(%)

|--------|- bus -|- bicycle -|- walk -|- other -|
|- bus  -|- 90  -|-   4  -|-    2   -|-    4     -|   
bicycle   7     86      1     6        
walk      8      7     80     5        
other    10      2      3     85          

假设该城市居民每天出行总人数为 468 万人次，出行人数不变，各出行方式的转移概率也不变，问题： 
（1） 预测2006年该城市乘公交出行的人数
（2） 经历足够长的时间，求出行方式的比例是多少？

分析：这是一个时间齐次马尔科夫过程，可根据转移矩阵的初始定义进行推断
 
第一问

In [ ]:
import numpy as np

data = np.matrix( [[90, 4, 2, 4],
                  [7, 86, 1, 6],
                  [8, 7, 80, 5],
                  [10, 2, 3, 85]] )

# 转移概率矩阵

In [ ]:
# 下一年的概率应该为当年分配概率和转移矩阵的乘积

```{r}
## 2003 年
p1 <- p%*%T

## 2004 年
p2 <- p1%*%T

## 2005 年
p3 <- p2%*%T

## 2006 年
p4 <- p3%*%T
```

2006 年乘坐公交车出行的总人数应为

```{r}
res <- 468 * p4[1]
```
 

第二问，用计算机模拟的方法，通过对转移矩阵的平衡状态近似求解

In [ ]:
 
```{r}
## 初始化一个空向量
s <- c()
 
## 假设一个人在初始时刻选择1公交车出行
s[1] <- 1
 
## 则其在t1时刻选择任何一种出行方式的概率如下
T[s[j-1],]
 
## 但是他选择的出行方式可以是随机的，故用sample按照前一个状态的概率，随机抽取一次
res <- sample(1:4, size = 1, prob = T[s[j-1],])
 
## 抽取的结果，就是t1时的状态
## 而 t2时的状态只受到t1时状态的影响，因此又回到T[s[j-1],]，至此完成一次模拟
 
## 每一次抽样都是只受到前一次抽样的影响
for (j in 2:50000)
   s[j] <- sample(1:4, size = 1, prob = T[s[j-1],])
```

在进行多次模拟后，马尔可夫链逐渐收敛. 模拟 50000 代的概率分配如下

```{r}
res <- table(s[1:50000])/50000
names(res) <- c("bus", "bicycle", "walk", "other")
```

题外

无论假设s[1] = 1,2,3 还是4，进行多次模拟后，所得的结果是非常接近的. 这也表明，马尔可夫过程的平衡状态与初始值无关.